WeatherForcast/Models/City.cs
using System.ComponentModel.DataAnnotations;

namespace WeatherForcast.Models
{
    public class City
    {
        [Display(Name ="City Name:")]
        public string Name { get; set; }

        [Display(Name = "Temperature:")]
        public float Temperature { get; set; }

        [Display(Name = "Humidity:")]
        public int Humidity { get; set; }

        [Display(Name = "Pressure:")]
        public int Pressure { get; set; }

        [Display(Name = "Wind Speed:")]
        public float Wind { get; set; }

        [Display(Name = "Weather Condition:")]
        public string Weather { get; set; }

        [Display(Name = "Max:")]
        public float TempMax { get; set; }

        [Display(Name = "Min:")]
        public float TempMin { get; set; }

        [Display(Name = "Feels Like:")]
        public float Feels_Like { get; set; }
    }

}

WeatherForcast/Models/ErrorViewModel.cs
namespace WeatherForcast.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WeatherForcast/ViewModels/Cloud.cs
namespace WeatherForcast.Models
{
    public class Cloud
    {
        public float h { get; set; }
    }
}

WeatherForcast/ViewModels/Coord.cs
namespace WeatherForcast.Models
{
    public class Weather
    {
        public float Id { get; set; }
        public string main { get; set; }

        public string description { get; set; }

        public string icon { get; set; }
    }
}

WeatherForcast/ViewModels/Rain.cs
namespace WeatherForcast.Models
{
    public class Rain
    {
        public string country { get; set; }
        public int sunrise { get; set; }
        public int sunset { get; set; }

    }
}

WeatherForcast/ViewModels/SearchBy.cs
using System.ComponentModel.DataAnnotations;

namespace WeatherForcast.Models
{
    public class SearchBy
    {
        [Required]
        [RegularExpression("[a-z A-Z]{3,}", ErrorMessage = "Invalid City Name Should Be English Only With More Than 2 characters")]

        [MaxLength(30, ErrorMessage = "Invalid City Name Should Be Less Than 30 Characters")]        
        public string Name { get; set; }    
    }
}

WeatherForcast/ViewModels/Sys.cs
namespace WeatherForcast.Models
{
    public class Sys
    {
        public float h { get; set; }
    }
}

WeatherForcast/ViewModels/Weather.cs
namespace WeatherForcast.Models
{
    public class Coord
    {
        public float Lon { get; set; }
        public float Lat { get; set; }

    }
}

WeatherForcast/ViewModels/WeatherResult.cs
using WeatherForcast.Models;

namespace WeatherForcast.ViewModels
{
    public class WeatherResult
    {
        public Coord coord { get; set; }
        public List<Weather> weather { get; set; }
        public main main { get; set; }
        public Wind wind { get; set; }
        public Rain rain { get; set; }
        public Cloud clouds { get; set; }
        public Sys sys { get; set; }

        public int timezone { get; set; }
        public int id { get; set; }
        public string name { get; set; }
        public int code { get; set; }







    }
}

WeatherForcast/ViewModels/Wind.cs
namespace WeatherForcast.Models
{
    public class Wind
    {
        public float speed { get; set; }
        public float degree { get; set; }
        public float gust { get; set; }

    }
}

WeatherForcast/ViewModels/main.cs
namespace WeatherForcast.Models
{
    public class main
    {
        public float temp { get; set; }
        public float feels_like { get; set; }
        public float temp_min { get; set; }
        public float temp_max { get; set; }
        public int pressure { get; set; }
        public int humidity { get; set; }
        public float sea_Level { get; set; }
        public float grnd_level { get; set; }




    }
}

WeatherForcast/Controllers/WeatherController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WeatherForcast.Models;
using WeatherForcast.Repositories;

namespace WeatherForcast.Controllers
{
    public class WeatherController : Controller
    {

        IWeatherRepository weatherRepository;
        public WeatherController(IWeatherRepository _weatherRepository)
        {
            weatherRepository= _weatherRepository;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(SearchBy city)
        {
            if (ModelState.IsValid)
            {
                var WeatherData = weatherRepository.GetWeatherData(city.Name);
                if (WeatherData == null)
                {
                    ModelState.AddModelError("", "Invalid Name No Matching");
                    return View(city);
                }
                var newcity = new City
                {
                    Name = WeatherData.name,
                    Humidity = WeatherData.main.humidity,
                    Pressure = WeatherData.main.pressure,
                    Temperature = WeatherData.main.temp,
                    Weather = WeatherData.weather[0].main ?? "Unknown",
                    Wind = WeatherData.wind.speed,
                    TempMax = WeatherData.main.temp_max,
                    TempMin = WeatherData.main.temp_min,
                    Feels_Like = WeatherData.main.feels_like
                };
                ViewBag.Data = newcity;
                return View();
            }
           return View(city);
        }

    }
}

WeatherForcast/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WeatherForcast</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WeatherForcast.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Weather" asp-action="Index">WeatherForecast</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Weather" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WeatherForcast 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WeatherForcast/Views/Weather/Index.cshtml
@model WeatherForcast.Models.SearchBy
@{
    ViewData["Title"] = "Weather Forcast";
    var ModelData = ViewBag.Data;
}
 <section class="vh-100">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-8 col-lg-6 col-xl-4">
        <div asp-validation-summary=All class="text-danger"></div>
        <h3 class="mb-4 pb-2 fw-normal">Check the weather forecast</h3>
        <form asp-action="Index" method="post">
            <div class="form-group mb-3">
              <input type="search" asp-for="Name" class="form-control rounded" placeholder="City" aria-label="Search"
                aria-describedby="search-addon" />
               <span asp-validation-for="Name" class="text-danger"></span>
            </div>
           <button type="submit" class="btn-primary btn">Search</button>
       </form>
       
        @if(ModelData != null)
        {
           <partial name="_WeatherResult" model=@ModelData/> 
        }

      </div>
    </div>
  </div>
</section>

WeatherForcast/Views/Weather/_WeatherResult.cshtml
@model WeatherForcast.Models.City
<div class="card card-shadow mt-2">
   <div class="card-body p-4">
     <h4 class="mb-1 sfw-normal">@Model.Name</h4>
     <div class="form-group">
         <label asp-for=Temperature class="form-label" ></label>
         <strong class="badge alert-primary">@Model.Temperature °C</strong>
         <div class="mb-2">
             Max: <strong class="badge alert-primary">@Model.Temperature °C</strong>, Min: <strong class="badge alert-primary">3.89°C</strong>
         </div>
     </div>

     <div class="form-group">
         <label asp-for=Humidity class="form-label" ></label>
         <strong class="badge alert-primary">@Model.Humidity</strong>   
     </div>
     <div class="form-group">
           <label asp-for=Feels_Like class="form-label"></label>
           <strong class="badge alert-primary">@Model.Feels_Like</strong>     
     </div>
      <div class="form-group">
            <label asp-for=Wind class="form-label" ></label>
            <strong class="badge alert-primary">@Model.Wind</strong>
     </div>
     <div class="form-group">
         <label asp-for=Weather class="form-label" ></label>
         <strong class="badge alert-primary">@Model.Weather</strong>
         @if(@Model.Weather == "Clouds")
            {
                
            }
        </div>
    
   </div>
</div>